import { ocorrencia } from "./types";

export const listaOcorrencias: ocorrencia[] = [
   {
      "id": 1,
      "dataNotificacao": "01/05/2019",
      "dataPrimeirosSintomas": "28/04/2019",
      "dataTeste": "30/04/2019",
      "dataObito": "30/05/2019",
      "dataNascimento": "20/08/1983",
      "faixaEtaria": "30 a 40",
      "etnia": "caucasiana",
      "bairro": "Córrego Grande",
      "cidade": "Florianópolis",
      "centroDeSaude": "CS CORREGO GRANDE",
      "tipoTeste": "RT-PCR",
      "genero": "Masculino",
      "dispneia": true,
      "febre": true,
      "tosse": true,
      "uti": true,
      "dorGarganta": true,
   },
   {
      "id": 2,
      "dataNotificacao": "05/5/2019",
      "dataPrimeirosSintomas": "30/04/2019",
      "dataTeste": "01/05/2019",
      "dataObito": "--",
      "dataNascimento": "03/06/1987",
      "faixaEtaria": "30 a 40",
      "etnia": "caucasiana",
      "bairro": "Córrego Grande",
      "cidade": "Florianópolis",
      "centroDeSaude": "CS CORREGO GRANDE",
      "tipoTeste": "RT-PCR",
      "genero": "Feminino",
      "dispneia": true,
      "febre": true,
      "tosse": true,
      "uti": true,
      "dorGarganta": true,
   },
   {
      "id": 1,
      "dataNotificacao": "01/05/2019",
      "dataPrimeirosSintomas": "28/04/2019",
      "dataTeste": "30/04/2019",
      "dataObito": "30/05/2019",
      "dataNascimento": "20/08/1983",
      "faixaEtaria": "30 a 40",
      "etnia": "caucasiana",
      "bairro": "Córrego Grande",
      "cidade": "Florianópolis",
      "centroDeSaude": "CS CORREGO GRANDE",
      "tipoTeste": "RT-PCR",
      "genero": "Masculino",
      "dispneia": true,
      "febre": true,
      "tosse": true,
      "uti": true,
      "dorGarganta": true,
   },
   {
      "id": 1,
      "dataNotificacao": "01/05/2019",
      "dataPrimeirosSintomas": "28/04/2019",
      "dataTeste": "30/04/2019",
      "dataObito": "30/05/2019",
      "dataNascimento": "20/08/1983",
      "faixaEtaria": "30 a 40",
      "etnia": "caucasiana",
      "bairro": "Córrego Grande",
      "cidade": "Florianópolis",
      "centroDeSaude": "CS CORREGO GRANDE",
      "tipoTeste": "RT-PCR",
      "genero": "Masculino",
      "dispneia": true,
      "febre": true,
      "tosse": true,
      "uti": true,
      "dorGarganta": true,
   },
   {
      "id": 1,
      "dataNotificacao": "01/05/2019",
      "dataPrimeirosSintomas": "28/04/2019",
      "dataTeste": "30/04/2019",
      "dataObito": "30/05/2019",
      "dataNascimento": "20/08/1983",
      "faixaEtaria": "30 a 40",
      "etnia": "caucasiana",
      "bairro": "Córrego Grande",
      "cidade": "Florianópolis",
      "centroDeSaude": "CS CORREGO GRANDE",
      "tipoTeste": "RT-PCR",
      "genero": "Masculino",
      "dispneia": true,
      "febre": true,
      "tosse": true,
      "uti": true,
      "dorGarganta": true,
   },
]